Update sharkfin-waydroid-utils-setup-wizard

diff --git a/files/system/shared/usr/libexec/sharkfin-waydroid-utils-setup-wizard b/files/system/shared/usr/libexec/sharkfin-waydroid-utils-setup-wizard
--- a/files/system/shared/usr/libexec/sharkfin-waydroid-utils-setup-wizard
+++ b/files/system/shared/usr/libexec/sharkfin-waydroid-utils-setup-wizard
@@ -8,6 +8,14 @@ if ! command -v zenity &> /dev/null; then
     echo "Error: zenity is not installed." >&2
     exit 1
 fi
+if ! command -v curl &> /dev/null; then
+    echo "Error: zenity is not installed." >&2
+    exit 1
+fi
+if ! command -v pkexec &> /dev/null; then
+    echo "Error: zenity is not installed." >&2
+    exit 1
+fi
 if [ -n "$system_type" ]
 then
   echo "DEBUG: Using the $system_type system type. "
